name: CI/CD Pipeline

on: 
  workflow_dispatch:
  push:
    branches: 
    - main
env:
  AZURE_WEBAPP_NAME: ems-user-api
  AZURE_WEBAPP_PACKAGE: "./publish"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with: 
           dotnet-version: '8.0.x'
      
      - name: Restore
        run: dotnet restore ./ems-be/UserManagementSolution/UserManagementSolution.sln

      - name: Build
        run: dotnet build ./ems-be/UserManagementSolution/UserManagementSolution.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./ems-be/UserManagementSolution/UserManagementSolution.sln --configuration Release --no-build

      - name: Azure Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE}}













      
