name: CI/CD Pipeline

on: 
  workflow_dispatch:
  push:
    branches: 
    - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with: 
           dotnet-version: '8.0.x'
      
      - name: Restore
        run: dotnet restore ./EMS/ems-be/UserManagementSolution.sln

      - name: Build
        run: dotnet build ./EMS/ems-be/UserManagementSolution.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./EMS/ems-be/UserManagementSolution.sln --configuration Release --no-build













      
